options:
  formatter: stylish
  merge-default-rules: false
files:
  include: "**/*.s+(a|c)ss"
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude:
      - breakpoint
      - mq

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    - include: true
      allow-single-line-rulesets: true
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 2
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 1
  no-transition-all: 1
  no-universal-selectors: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 0
  property-units: 0

  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 0
  force-element-nesting: 1
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 2
    - allow-leading-underscore: true
      convention: ^[-_a-zA-Z0-9]+$
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: ^[-_a-zA-Z0-9]+$
  id-name-format:
    - 1
    - allow-leading-underscore: true
      convention: ^[-_a-zA-Z0-9]+$
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: ^[-_a-zA-Z0-9]+$
  placeholder-name-format: 1
  variable-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase

  # Style Guide
  attribute-quotes: 2
  bem-depth:
    - 1
    - max-depth: 2
  border-zero:
    - 2
    - convention: none
  brace-style:
    - style: stroustrup
      allow-single-line: false
  clean-import-paths:
    - 2
    - leading-underscore: false
      filename-extension: false
  empty-args:
    - 2
    - include: false
  hex-length:
    - 2
    - style: long
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: true
  max-file-line-count:
    - 2
    - length: 2000
  max-line-length:
    - 2
    -  length: 200
  nesting-depth:
    - 2
    - max-depth: 5
  pseudo-element: 2
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit:
    - 1
    - include: false

  # Inner Spacing
  space-after-comma:
    - 2
    - include: true
  space-before-colon:
    - 1
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-after-bang:
    - 1
    - include: false
  space-between-parens:
    - 1
    - include: false
  space-around-operator:
    - 1
    - include: true

  # Final Items
  trailing-semicolon: 2
  final-newline: 2

  # SMACSS Property Order
  # http://smacss.com/book/formatting
  # Based on: https://github.com/brigade/scss-lint/blob/master/data/property-sort-orders/smacss.txt

  property-sort-order:
    - 1
    -
      order:
        # Box
        - 'display'
        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'

        - 'flex'
        - 'flex-basis'
        - 'flex-direction'
        - 'flex-flow'
        - 'flex-grow'
        - 'flex-shrink'
        - 'flex-wrap'
        - 'align-content'
        - 'align-items'
        - 'align-self'
        - 'justify-content'
        - 'order'

        - 'width'
        - 'min-width'
        - 'max-width'

        - 'height'
        - 'min-height'
        - 'max-height'

        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'

        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'

        - 'float'
        - 'clear'

        - 'columns'
        - 'column-gap'
        - 'column-fill'
        - 'column-rule'
        - 'column-span'
        - 'column-count'
        - 'column-width'

        - 'transform'
        - 'transform-box'
        - 'transform-origin'
        - 'transform-style'

        - 'transition'
        - 'transition-delay'
        - 'transition-duration'
        - 'transition-property'
        - 'transition-timing-function'

        # Border
        - 'border'
        - 'border-top'
        - 'border-right'
        - 'border-bottom'
        - 'border-left'
        - 'border-width'
        - 'border-top-width'
        - 'border-right-width'
        - 'border-bottom-width'
        - 'border-left-width'

        - 'border-style'
        - 'border-top-style'
        - 'border-right-style'
        - 'border-bottom-style'
        - 'border-left-style'

        - 'border-radius'
        - 'border-top-left-radius'
        - 'border-top-right-radius'
        - 'border-bottom-left-radius'
        - 'border-bottom-right-radius'

        - 'border-color'
        - 'border-top-color'
        - 'border-right-color'
        - 'border-bottom-color'
        - 'border-left-color'

        - 'outline'
        - 'outline-color'
        - 'outline-offset'
        - 'outline-style'
        - 'outline-width'

        # Background
        - 'background'
        - 'background-attachment'
        - 'background-clip'
        - 'background-color'
        - 'background-image'
        - 'background-repeat'
        - 'background-position'
        - 'background-size'

        # Text
        - 'color'

        - 'font'
        - 'font-family'
        - 'font-size'
        - 'font-smoothing'
        - 'font-style'
        - 'font-variant'
        - 'font-weight'

        - 'letter-spacing'
        - 'line-height'
        - 'list-style'

        - 'text-align'
        - 'text-decoration'
        - 'text-indent'
        - 'text-overflow'
        - 'text-rendering'
        - 'text-shadow'
        - 'text-transform'
        - 'text-wrap'

        - 'white-space'
        - 'word-spacing'

        # Other
        - 'border-collapse'
        - 'border-spacing'
        - 'box-shadow'
        - 'caption-side'
        - 'content'
        - 'cursor'
        - 'empty-cells'
        - 'opacity'
        - 'overflow'
        - 'quotes'
        - 'speak'
        - 'table-layout'
        - 'vertical-align'
        - 'visibility'
        - 'z-index'
      ignore-custom-properties: true
